### ISSUE TITLE
[Feature] multiple keybinds for multiple languages

### ISSUE THREAD

**Issue by Nicolas-GE** [Elypha/BilingualTooltips#1]
it'd be cool to be able to assign multiple keybinds, for example if i speak french and german to be able to see the french one with one keybind, and the german one with another, english being display language

**Comment by Elypha** [comment]
very valid. this may require some rework in other parts of the plugin and I'll probably ship it together with the next release (hopefully soon)

**Comment by Elypha** [comment]
keep adding hotkeys for each extra feature seems not very decent. it'll be implemented as a separate sub window and when a configured hotkey is activated when you hover over an item/action, the window will pop up and you can configure the languages to show there and their order
I hope this works for your use case. have been a bit busy irl so 7.1 compatibility first and the update will come later

**Comment by Nicolas-GE** [comment]
that works and doesn't clutter keybinds, good idea!

**Comment by Elypha** [comment]
this is now implemented in 1.1.0.0. please give it a try.
